#!/bin/sh
cd "$(dirname "$(readlink -f "$0")")"

(
    printf '// generated by make-version.sh\n'
    printf '// DO NOT COMMIT!\n'
    printf '#define KUEMMELRECORDER_VERSION "%s"\n' "$(git describe --tags --always)"
) > version.h

(
    v="$(git describe --tags)"
    v="${v#v}"
    v="${v%%-*}"
    printf 'rem generated by make-version.sh\r\n'
    printf 'rem DO NOT COMMIT!\r\n'
    printf 'set KUEMMELRECORDER_VERSION=%s\r\n' "$v"
) > version.inc.bat
