#!/bin/sh
cd "$(dirname "$(readlink -f "$0")")"

(
    printf '// generated by make-version.sh\n'
    printf '// DO NOT COMMIT!\n'
    printf '#define KUEMMELRECORDER_VERSION "%s"\n' "$(git describe --tags --always)"
) > version.h
